package com.ruoyi.wxcustomer.domain;

import java.util.Date;

import com.ruoyi.common.core.domain.BaseEntity;

public class KhAssetsDetail extends BaseEntity{
    private static final long serialVersionUID = 1L;

   /**
    * 主键
    */
    private String id;

     /**
      * 关联业务id
      */
    private String assetsId;
    /**
     * 微信名
     */
    private String wechatName;

    /**
     * 套餐详情
     */
    private String mealDetail;

     /**
      * 是否异常
      */
    private String isAbnormal;

     /**
      * 检查发圈日期
      */
    private Date checkDate;

     /**
      * 发圈数量
      */
    private Integer ringsCount;

     /**
      * 微信好友数量
      */
    private Integer firendCount;

     /**
      *抖音粉丝
      */
    private String jitterFans;

     
    public String getId() {
        return id;
    }

     
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    
    public String getAssetsId() {
        return assetsId;
    }

     
    public void setAssetsId(String assetsId) {
        this.assetsId = assetsId == null ? null : assetsId.trim();
    }

    
    public String getWechatName() {
        return wechatName;
    }

    
    public void setWechatName(String wechatName) {
        this.wechatName = wechatName == null ? null : wechatName.trim();
    }

     
    public String getMealDetail() {
        return mealDetail;
    }

     
    public void setMealDetail(String mealDetail) {
        this.mealDetail = mealDetail == null ? null : mealDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_assets_detail.is_abnormal
     *
     * @return the value of kh_assets_detail.is_abnormal
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public String getIsAbnormal() {
        return isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_assets_detail.is_abnormal
     *
     * @param isAbnormal the value for kh_assets_detail.is_abnormal
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public void setIsAbnormal(String isAbnormal) {
        this.isAbnormal = isAbnormal == null ? null : isAbnormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_assets_detail.check_date
     *
     * @return the value of kh_assets_detail.check_date
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_assets_detail.check_date
     *
     * @param checkDate the value for kh_assets_detail.check_date
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_assets_detail.rings_count
     *
     * @return the value of kh_assets_detail.rings_count
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public Integer getRingsCount() {
        return ringsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_assets_detail.rings_count
     *
     * @param ringsCount the value for kh_assets_detail.rings_count
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public void setRingsCount(Integer ringsCount) {
        this.ringsCount = ringsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_assets_detail.firend_count
     *
     * @return the value of kh_assets_detail.firend_count
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public Integer getFirendCount() {
        return firendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_assets_detail.firend_count
     *
     * @param firendCount the value for kh_assets_detail.firend_count
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public void setFirendCount(Integer firendCount) {
        this.firendCount = firendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_assets_detail.jitter_fans
     *
     * @return the value of kh_assets_detail.jitter_fans
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public String getJitterFans() {
        return jitterFans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_assets_detail.jitter_fans
     *
     * @param jitterFans the value for kh_assets_detail.jitter_fans
     *
     * @mbggenerated Mon Feb 10 19:44:00 CST 2020
     */
    public void setJitterFans(String jitterFans) {
        this.jitterFans = jitterFans == null ? null : jitterFans.trim();
    }
}